parameters:
    ns.security.query.class: NS\SecurityBundle\Doctrine\SecuredQuery
    ns.security.acl_converter.class: NS\SecurityBundle\Role\ACLConverter

services:
  ns_security.acl_autocompleter:
    class: NS\SecurityBundle\Form\Types\ACLAutoCompleterType
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type, alias: acl_object_target_autocompleter }

  ns.security.acl_converter:
    class: %ns.security.acl_converter.class%
    arguments: [ "@security.role_hierarchy" ]

  ns.security.query:
    class: %ns.security.query.class%
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns.security.acl_converter" ]

  ns.model_manager:
      public: false
      class: NS\SecurityBundle\Model\Manager
      decorates: doctrine.orm.default_entity_manager
      arguments: [ "@ns.model_manager.inner" ]
      calls:
        - [ setSecuredQuery, [ "@ns.security.query" ] ]

  ns.security.authentication.listener:
    class: NS\SecurityBundle\Auth\AdminListener
    parent: security.authentication.listener.abstract
    abstract: true

  security.authentication_provider.ns_security:
    class: NS\SecurityBundle\Auth\AdminAuthenticationProvider
    abstract: true
    public: false
    arguments: [ '', "@security.user_checker", '', "@security.encoder_factory", %security.authentication.hide_user_not_found% ]
