services:
  ns_security.acl_autocompleter:
    class: NS\SecurityBundle\Form\Types\ACLAutoCompleterType
    arguments: [ "@doctrine.orm.entity_manager" ]
    tags:
      - { name: form.type, alias: acl_object_target_autocompleter }

  ns_security.acl_converter:
    class: NS\SecurityBundle\Role\ACLConverter
    arguments: [ "@security.role_hierarchy" ]

  ns_security.query:
    class: NS\SecurityBundle\Doctrine\SecuredQuery
    arguments: [ "@security.token_storage", "@security.authorization_checker", "@ns_security.acl_converter" ]
    lazy: true

  ns_security.model_manager:
      public: false
      class: NS\SecurityBundle\Model\Manager
      decorates: doctrine.orm.default_entity_manager
      arguments: [ "@ns_security.model_manager.inner" ]
      calls:
        - [ setSecuredQuery, [ "@ns_security.query" ] ]

  ns.security.authentication.listener:
    class: NS\SecurityBundle\Auth\AdminListener
    parent: security.authentication.listener.abstract
    abstract: true

  security.authentication_provider.ns_security:
    class: NS\SecurityBundle\Auth\AdminAuthenticationProvider
    abstract: true
    public: false
    arguments: [ '', "@security.user_checker", '', "@security.encoder_factory", "%security.authentication.hide_user_not_found%" ]

